### PR TITLE
Add Geo Polygon Filter Local Mode

### PR DESCRIPTION
**Pull request by zzzz-vincent**
As Geo Polygon Filter (https://github.com/qdrant/qdrant/issues/795) is being implemented, the local mode should also keep updated with it.

This change includes:

- introduce Shapely as a python library for geo spatial geometry
- implement local model polygon filter
- add new test

### CODE REVIEW

**Comment by joein** [comment]
Hi @zzzz-vincent 

Not sure whether this PR requires a review at the moment, ask for review once it is ready :)

**Comment by agourlay** [comment]
I think it will make sense to review this once the Rust implementation is reaching the finish line.

@joein Do you have any experience with the Shapely Python library?

**Comment by joein** [comment]
@agourlay I don't

**Comment by agourlay** [comment]
@zzzz-vincent Have you thought about how to add the multi-polygon support with Shapely as well?

**Comment by generall** [comment]
Hi @zzzz-vincent, Please rebase your changes to `dev` branch

**Comment by agourlay** [comment]
superseded by https://github.com/qdrant/qdrant-client/pull/272

**Pull request closed without merging**
