### PR TITLE
Use `mypy-protobuf` for better grpc type stubs

### PR DESCRIPTION
**Pull request by coszio**
This adds mypy type stub generation for better DX with grpc types. 

- Adds `mypy-protobuf` to poetry dev dependencies
- Adds `--mypy_out` flag to grpc client generator

`dev`:
image

PR:
image

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### CODE REVIEW

**Comment by coszio** [comment]
Recreated the type stubs with the dev branch of qdrant core

**Comment by coszio** [comment]
@joein anything against this? Otherwise I think it makes our life easier

**Comment by joein** [comment]
Let's merge it before 1.11.2, but not right now

**Review by joein — APPROVED** [review]

**Comment by coszio** [comment]
I added the mypy stubs in #758, now that this one is approved. To not repeat client generation, I will close this one in favor of the other one.

**Pull request closed without merging**
