### PR TITLE
Update README.md, fastembed the way to save it 

### PR DESCRIPTION
**Pull request by VinciGit00**
Screenshot 2024-09-28 alle 16 48 23

Now you have to write > pip install fastembed

### CODE REVIEW

**Comment by generall** [comment]
i don't think I understand this change. the document  section is about integration with qdrant

**Comment by VinciGit00** [comment]
The command was updated

**Comment by joein** [comment]
@VinciGit00 could you try installing it with `pip3 install "qdrant-client[fastembed]"` ? (with the quotes, since zsh require them)

**Comment by VinciGit00** [comment]
Screenshot 2024-10-02 alle 13 52 23

**Comment by joein** [comment]
that's correct, qdrant-client supports gpu as of v1.9.2

**Pull request closed without merging**
