### PR TITLE
Check vectors for NaN in local mode: Fixes #495

### LINKED ISSUE #495: Check vectors for NaN in local mode

### PR DESCRIPTION
**Pull request by Ya-shh**
I have covered the necessary steps to check vectors for NaN values in local mode. 

These modifications ensure that any vector data being inserted or updated through these methods is checked for NaN values, preventing the insertion of invalid vector data into the local Qdrant collection. This is crucial for maintaining the integrity of the vector search operations, as NaN values in vectors can lead to unexpected behavior or errors during search and retrieval operations.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you installed `pre-commit` with `pip3 install pre-commit` and set up hooks with `pre-commit install`?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by Ya-shh** [comment]
@joein , I have done all the tasks including reverting commits and also added a test to ensure that this code is launchable

**Comment by Ya-shh** [comment]
Hey !@joein & @generall  I have successfully added checks for NaN in local mode. Previously the code was not working in local mode but now it's working.

**Comment by Ya-shh** [comment]
@joein could you please review this PR?

**Comment by Ya-shh** [comment]
Could anyone please verify the changes ?

**Comment by joein** [comment]
@Ya-shh I'll review it a little bit later today

**Comment by joein** [comment]
Hey @Ya-shh 

Thank you for your contribution!

Unfortunately, there are some problems with it, and it will be easier to rewrite it :(

1) We ask contributors changes to point to `dev` branch, i.e. take latest `dev` branch, create a branch and then create a pull request to `dev`
2) The PR itself a little bit entangled, comments might not that critical, however describing them might take a lot of time

Nevertheless, we are really grateful for you, while I was reviewing your PR, I found one bug in our code (#559)

Looking forward to your following endeavours 👍

**Comment by Ya-shh** [comment]
No worries @joein , I got to know my mistakes thank you for that .

**Comment by joein** [comment]
@Ya-shh  #560

**Pull request closed without merging**
