### PR TITLE
new: retry mechanism in migrate

### PR DESCRIPTION
**Pull request by joein**
#385 

It's not that elegant, but should mitigate the consequences of rare timeouts

### CODE REVIEW

**Review by generall — COMMENTED** [review]
not elegant indeed

**Comment by LemurPwned** [comment]
Hey, is there any hope for having this merged? It stops pretty frequently for large collections in my case.

**Comment by joein** [comment]
Hey @LemurPwned 
Which error do you observe? 
could you show us your traceback?

**Comment by jmohren** [comment]
Is there any update here? :)

**Comment by joein** [comment]
closing in favour of #706

**Pull request closed without merging**
